version: '3'
services:
  producer: &ortelius-app
#    image: "avaplatform/ortelius:fb08d10"
    build:
      context: ../..
    command: ["stream", "producer"]
    networks:
      - services
    external_links:
      - zookeeper
      - kafka
      - mysql
      - redis
    volumes:
      - gecko-ipcs:/tmp
      - ../config.json:/opt/config.json
    restart: on-failure
  indexer:
    <<: *ortelius-app
    command: ["stream", "indexer"]
  api:
    <<: *ortelius-app
    command: ["api"]
    ports:
      - 8080:8080
networks:
  services:
    external:
      name: ortelius_services
volumes:
  gecko-ipcs:
    external:
      name: ortelius_gecko_ipcs
